### ISSUE TITLE
Feature request: add a flag that exposes the actual failure error message with filename and line number

### ISSUE THREAD

**Issue by gmlewis** [bitfield/gotestdox#4]
This looks like a cool tool and a cool idea, but as it currently stands, it hides useful results and hinders productivity because it doesn't report the actual error along with the filename and line number.

For example, I spend a great deal of time in a large Go codebase where I'm frequently running a script within my text editor (Emacs) that runs `go test -race ./...`. I intentionally broke one of the methods in order to try out `gotestdox` and I get this:

```
...lots-of-success-lines...
 x FederatedAnalysis parse job params multi-word command with unused string args (0.00s)
...lots-more-lines...
[go test -json -race ./...] exit status 1
```

However, when I run `go test -race ./...` (or my script) I get this:

```
...lots-of-success-lines...
ok  	github.com/gmlewis/federated-fiber/cmd/writeParquet2dgraph	(cached)
--- FAIL: TestFederatedAnalysis_ParseJobParams (0.01s)
    --- FAIL: TestFederatedAnalysis_ParseJobParams/multi-word_command_with_unused_string_args (0.00s)
        federated-analysis_test.go:423: FederatedAnalysis.ParseJobParams() error = missing command, wantErr false
FAIL
FAIL	github.com/gmlewis/federated-fiber/common	0.028s
...lots-more-lines...
FAIL
```

Note that here, I can see the actual error but more importantly, the filename and line number.
This allows me to use the existing tooling I have already working to immediately jump ("C-x `") to the next error and work on fixing it which is huge especially for large refactors.

If you added a flag that copied this line to the output, then the tooling could jump to the error and you could see what the actual error was, and not just a summary.

Also, I see that there currently is no flag parsing at all, so `gotestdox -h` doesn't do what I expected.
If you support flag parsing, you might have to add `--` to separate `gotestdox` flags from `go test` flags.

Thank you!

**Comment by bitfield** [comment]
This is a great suggestion, thank you! And congratulations on reporting the first issue, no doubt of any.

On careful consideration, I don't think this is something I want to add. It's worth saying that there are many delightful tools to present Go test output in various useful ways, and very likely one of them already does what you want.

`gotestdox` isn't _really_ a test reporter, though. Its purpose is to help you think about and maybe improve your test names, and also to generate a simple-minded kind of documentation about your API.

Now, if we're going to print statements about what the tests claim the program does, it's important to actually _verify_ those statements. If one of the tests happens to be failing, it would be incorrect to print its name as a true statement about the program's behaviour. That's why `gotestdox` reports the test status with either a checkmark or a cross.

Beyond that, though, `gotestdox` is not concerned about _why_ the test is failing, only that it _is_ failing. So I think it says as much as it needs to, and no more.

> Also, I see that there currently is no flag parsing at all, so gotestdox -h doesn't do what I expected.

That's correct. There are no flags, because none are needed. I tend to think the best programs are the ones that don't need flags, or even arguments.

Again, thanks for the report, and please keep the suggestions coming.

**Comment by sheldonhull** [comment]
I do like what this offers. Very nice work and blog post. 

The lack of any error output at all is a little confusing. I was considering plugging this into my github actions instead of `gotestsum`, but without a few lines at the end of the error, it doesn't let me have any context without rerunning the same test manually to find that output. 

Examples... note I prefer the output from your tool and tparse in general. It's so clean.

I think the skip/error having a little output at the end might be worth considering, as I'd love to plug this into my pre-commit work, but without a little more error output I'd end up doubling my work.
Maybe that's fine for your intended usage, just wanted to say thanks and give one other piece of related feedback here. 

No skip shown fyi.

![2022-08-26-17 24 45-Code - Insiders-gotools go — magetools](https://user-images.githubusercontent.com/3526320/186998358-001ab23b-6089-45f0-a7c9-9614d8ddaed3.png)

![2022-08-26-17 19 15-Code - Insiders-gotools go — magetools](https://user-images.githubusercontent.com/3526320/186997959-00d6a9e6-0f34-457b-85d2-c42c068f31fb.png)

![2022-08-26-17 23 51-Code - Insiders-gotools go — magetools](https://user-images.githubusercontent.com/3526320/186998314-98e612ba-f58e-4f4c-a4c3-320b20600d61.png)

thanks! Always love your thoughtful posts 👍🏻

**Comment by bitfield** [comment]
> The lack of any error output at all is a little confusing. I was considering plugging this into my github actions

Right, but as we've discussed, `gotestdox` is explicitly not a tool for formatting the output of your tests. It presumes that your tests are _passing_, and tells you what the names of your tests assert about the behaviour of your program. Its only concession to the idea that some tests might _fail_ is to exit with a non-zero status, to stop CI pipelines.

You could, for example, pipe the output of `go test -json` through a program that gives you more context about failing tests, and _also_ through `gotestdox` to see the behaviour sentences.

Skipped tests are not run, by definition, so they assert nothing whatsoever about the behaviour of your program. Accordingly, `gotestdox` ignores them.

**Comment by bitfield** [comment]
@gmlewis and @sheldonhull, I don't know if you're still interested in `gotestdox`, but if so, perhaps you'll be pleased to know that I've added output for failing tests (and a usage message triggered by `-h`) in `v0.2.0`. Users are always right, except when they're not, and on this occasion the people have spoken!
